apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: getenvs.ai.platform.example.org
spec:
  compositeTypeRef:
    apiVersion: ai.platform.example.org/v1alpha1
    kind: Getenv
  mode: Pipeline
  pipeline:
  - step: environmentConfigs
    functionRef:
      name: crossplane-contrib-function-environment-configs
    input:
      apiVersion: environmentconfigs.fn.crossplane.io/v1beta1
      kind: Input
      spec:
        environmentConfigs:
        - type: Reference
          ref:
            name: example-config

  - step: compose
    functionRef:
      name: upbound-configuration-env-configcompose

  - step: crossplane-contrib-function-auto-ready
    functionRef:
      name: crossplane-contrib-function-auto-ready
